/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mshoukath' at '9/10/16 2:25 PM' with Gradle 2.13
 *
 * @author mshoukath, @date 9/10/16 2:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
